# type: "position_controllers/JointPositionController"
# joint: camera_slider
type: velocity_controllers/JointVelocityController
joint: camera_slider
# pid: {p: 1.0, i: 0.001, d: .01}
pid: {p: 12.0, i: 10.0, d: 0.0}
# pid: {p: 100.0, i: 0.01, d: 100.0  }
# pid: {p: 22.0, i: 0.1, d: 0.5}
# pid: {p: 100.0, i: 0.01, d: 2.5  }